version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-mst/test}
    command: ${TEST_CMD:-go test ./test/...}
    links:
      - service
    environment:
      - GRPC_HOST=service
      - GRPC_PORT=8090

  service:
    image: pipdevs/pip-services-sessions-node:latest
